application: quoraplus498
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: jinja2
  version: latest

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: web.app
