application: srikanth-udacity
version: latest
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /html
  static_dir: ../Client

- url: /.*
  script: web.app
  login: required

